name: Run Backend

on: push

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"a

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run backend
        run: python ATS_RESUME_backend/main.py
